version: '3'

services:
  # web:
  #   build: .
  #   command: yarn dev
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password